version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  
    volumes:
      - ./frontend/client:/usr/src/app/client  
    environment:
      - NODE_ENV=production
    depends_on:
      - backend  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    volumes:
      - ./backend:/app 
    environment:
      - NODE_ENV=development  
